
; Choose hardware: V1 or V2
[platformio]
default_envs = V1

[env]
platform        = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.34/platform-espressif32.zip
board           = WS-ESP32-S3-LCD-1-85C
framework       = arduino
board_upload.flash_size    = 16MB
board_upload.maximum_size  = 16777216
board_build.partitions     = default_16MB.csv
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
monitor_speed = 115200

build_flags =
  -w
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

[env:V1]
build_flags = ${env.build_flags} -DHARDWARE_V1
lib_ignore = Audio_ES8311, es8311, es7210, MIC_MSM, ESP_I2S, ESP_SR

[env:V2]
build_flags = ${env.build_flags} -DHARDWARE_V2
lib_ignore = Audio_PCM5101, MIC_MSM, ESP_I2S, ESP_SR
