// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Player

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel_volume = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel_volume, 77);
lv_obj_set_height( ui_Panel_volume, 206);
lv_obj_set_x( ui_Panel_volume, 279 );
lv_obj_set_y( ui_Panel_volume, 39 );
lv_obj_clear_flag( ui_Panel_volume, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel_volume, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_volume, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel_volume, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel_volume, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arc_Volume = lv_arc_create(ui_Panel_volume);
lv_obj_set_width( ui_Arc_Volume, 340);
lv_obj_set_height( ui_Arc_Volume, 340);
lv_obj_set_x( ui_Arc_Volume, -286 );
lv_obj_set_y( ui_Arc_Volume, -49 );
lv_arc_set_value(ui_Arc_Volume, 50);
lv_arc_set_bg_angles(ui_Arc_Volume,310,380);
lv_obj_set_style_arc_width(ui_Arc_Volume, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc_Volume, lv_color_hex(0xADADAD), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc_Volume, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc_Volume, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc_Volume, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc_Volume, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Panel_brightness = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel_brightness, 77);
lv_obj_set_height( ui_Panel_brightness, 206);
lv_obj_set_x( ui_Panel_brightness, 5 );
lv_obj_set_y( ui_Panel_brightness, 39 );
lv_obj_clear_flag( ui_Panel_brightness, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel_brightness, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_brightness, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel_brightness, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel_brightness, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arc_Brightness = lv_arc_create(ui_Panel_brightness);
lv_obj_set_width( ui_Arc_Brightness, 340);
lv_obj_set_height( ui_Arc_Brightness, 340);
lv_obj_set_x( ui_Arc_Brightness, -14 );
lv_obj_set_y( ui_Arc_Brightness, -49 );
lv_arc_set_value(ui_Arc_Brightness, 50);
lv_arc_set_bg_angles(ui_Arc_Brightness,160,230);
lv_obj_set_style_arc_width(ui_Arc_Brightness, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc_Brightness, lv_color_hex(0xADADAD), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc_Brightness, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc_Brightness, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Arc_Brightness, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc_Brightness, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Arc_Brightness, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Container_controlls = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container_controlls);
lv_obj_set_width( ui_Container_controlls, 212);
lv_obj_set_height( ui_Container_controlls, 66);
lv_obj_set_x( ui_Container_controlls, 0 );
lv_obj_set_y( ui_Container_controlls, 12 );
lv_obj_set_align( ui_Container_controlls, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container_controlls,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container_controlls, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container_controlls, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container_controlls, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container_controlls, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button_Previous = lv_btn_create(ui_Container_controlls);
lv_obj_set_width( ui_Button_Previous, 54);
lv_obj_set_height( ui_Button_Previous, 54);
lv_obj_set_x( ui_Button_Previous, 25 );
lv_obj_set_y( ui_Button_Previous, 21 );
lv_obj_set_align( ui_Button_Previous, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button_Previous, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button_Previous, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button_Previous, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_Previous, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_Previous, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Button_Previous, &ui_img_1799517327, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_src( ui_Button_Previous, &ui_img_1799517327, LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_img_opa(ui_Button_Previous, 150, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Button_PlayPause = lv_btn_create(ui_Container_controlls);
lv_obj_set_width( ui_Button_PlayPause, 54);
lv_obj_set_height( ui_Button_PlayPause, 54);
lv_obj_set_x( ui_Button_PlayPause, 25 );
lv_obj_set_y( ui_Button_PlayPause, 21 );
lv_obj_set_align( ui_Button_PlayPause, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Button_PlayPause, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_Button_PlayPause, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button_PlayPause, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button_PlayPause, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_PlayPause, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_PlayPause, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Button_PlayPause, &ui_img_1898897582, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_color(ui_Button_PlayPause, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button_PlayPause, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_Button_PlayPause, &ui_img_1779231396, LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_color(ui_Button_PlayPause, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Button_PlayPause, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_img_src( ui_Button_PlayPause, &ui_img_1898897582, LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_img_opa(ui_Button_PlayPause, 150, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Button_Next = lv_btn_create(ui_Container_controlls);
lv_obj_set_width( ui_Button_Next, 54);
lv_obj_set_height( ui_Button_Next, 54);
lv_obj_set_x( ui_Button_Next, 25 );
lv_obj_set_y( ui_Button_Next, 21 );
lv_obj_set_align( ui_Button_Next, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button_Next, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button_Next, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button_Next, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button_Next, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_Next, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Button_Next, &ui_img_1997223691, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_src( ui_Button_Next, &ui_img_1997223691, LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_img_opa(ui_Button_Next, 150, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Bar1 = lv_bar_create(ui_Screen1);
lv_bar_set_value(ui_Bar1,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar1, 235);
lv_obj_set_height( ui_Bar1, 10);
lv_obj_set_x( ui_Bar1, 4 );
lv_obj_set_y( ui_Bar1, -44 );
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x2BDDCE), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Roller_list = lv_roller_create(ui_Screen1);
lv_roller_set_options( ui_Roller_list, "Song Title", LV_ROLLER_MODE_NORMAL );
lv_roller_set_selected( ui_Roller_list, 1, LV_ANIM_OFF);
lv_obj_set_width( ui_Roller_list, 211);
lv_obj_set_height( ui_Roller_list, 103);
lv_obj_set_x( ui_Roller_list, 0 );
lv_obj_set_y( ui_Roller_list, 117 );
lv_obj_set_align( ui_Roller_list, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_Roller_list, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_list, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Roller_list, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Roller_list, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Roller_list, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Roller_list, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_list, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_list, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Roller_list, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Roller_list, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Roller_list, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Roller_list, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Roller_list, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Roller_list, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Roller_list, lv_color_hex(0x2BDDCE), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller_list, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller_list, &lv_font_montserrat_18, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller_list, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller_list, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Label_Time = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label_Time, 107);
lv_obj_set_height( ui_Label_Time, 16);
lv_obj_set_x( ui_Label_Time, 65 );
lv_obj_set_y( ui_Label_Time, -26 );
lv_obj_set_align( ui_Label_Time, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Time,"10:10");
lv_obj_set_style_text_align(ui_Label_Time, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel_devider = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel_devider, 235);
lv_obj_set_height( ui_Panel_devider, 3);
lv_obj_set_x( ui_Panel_devider, 0 );
lv_obj_set_y( ui_Panel_devider, 60 );
lv_obj_set_align( ui_Panel_devider, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel_devider, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel_devider, lv_color_hex(0x202420), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_devider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel_devider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image5, &ui_img_1224885811);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_Image5, -134 );
lv_obj_set_y( ui_Image5, 60 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image6 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image6, &ui_img_267335790);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_Image6, 137 );
lv_obj_set_y( ui_Image6, 60 );
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button_Mode = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button_Mode, 71);
lv_obj_set_height( ui_Button_Mode, 71);
lv_obj_set_x( ui_Button_Mode, 0 );
lv_obj_set_y( ui_Button_Mode, -120 );
lv_obj_set_align( ui_Button_Mode, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button_Mode, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button_Mode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button_Mode, lv_color_hex(0xFF4439), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button_Mode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Button_Mode, &ui_img_295812069, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_color(ui_Button_Mode, lv_color_hex(0xFF4439), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Button_Mode, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_Button_Mode, &ui_img_1947372027, LV_PART_MAIN | LV_STATE_CHECKED );

}
