// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Player

#ifndef _PLAYER_UI_H
#define _PLAYER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel_volume;
extern lv_obj_t *ui_Arc_Volume;
extern lv_obj_t *ui_Panel_brightness;
extern lv_obj_t *ui_Arc_Brightness;
extern lv_obj_t *ui_Container_controlls;
extern lv_obj_t *ui_Button_Previous;
extern lv_obj_t *ui_Button_PlayPause;
extern lv_obj_t *ui_Button_Next;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_Roller_list;
extern lv_obj_t *ui_Label_Time;
extern lv_obj_t *ui_Panel_devider;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Button_Mode;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1799517327);   // assets/Images/icon-previous.png
LV_IMG_DECLARE( ui_img_1898897582);   // assets/Images/icon-play.png
LV_IMG_DECLARE( ui_img_1779231396);   // assets/Images/icon-pause.png
LV_IMG_DECLARE( ui_img_1997223691);   // assets/Images/icon-next.png
LV_IMG_DECLARE( ui_img_1224885811);   // assets/Images/icon-brightness.png
LV_IMG_DECLARE( ui_img_267335790);   // assets/Images/icon-volume.png
LV_IMG_DECLARE( ui_img_295812069);   // assets/Images/icon-music.png
LV_IMG_DECLARE( ui_img_1947372027);   // assets/Images/icon-radio.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
